---
- name: Ensure Redis is installed
  yum:
    name: redis
    # state: present, in order not to upgrade any package to an untested version
    state: present
  become: yes
  tags: redis-service

- name: Ensure Redis is started
  service:
    name: redis
    state: started
    enabled: yes
  become: yes
  tags: redis-service
